### ISSUE TITLE
Gateway URL for Alipay sandbox is wrong

### ISSUE THREAD

**Issue by juny4ng** [Kaligo/alipay-global#2]
Sandbox URL should be "https://openapi.alipaydev.com/gateway.do?"

Right now it's set to this:

`def self.gateway_url
      AlipayGlobal.environment == "PRODUCTION" ? "https://mapi.alipay.com/gateway.do?" : "https://mapi.alipay.net/gateway.do?"
    end
`

**Comment by melvrickgoh** [comment]
fixed with https://github.com/Kaligo/alipay-global/pull/3
